version: 2.1

jobs:
  build-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            env
            echo "_______"
            docker build -f docker/Dockerfile.linux.amd64 -t something .

workflows:
  build-docker:
    jobs:
      - build-docker
